### ISSUE TITLE
Support most recent brian2 release: pytest update and Python 3 support

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#200]
This is a ZenHub Epic issue, collecting the steps needed to transition to Python 3 support.

## 1. Transition from `nosetest` to `pytest` (#169, #170, #171)
1. [x] Support last brian2 version that used `nosetest` (brian-team/brian2@dc6fa7987b66dafe62a731759343a73bee9ca25a)
    - This includes updating all brian2 changes from brian2 version 2.1.3 (our currently supported version) to that commit (2.2.2.1+git)
    - This should also fix #169 and maybe #170 (which itself is an Epic issue, collecting some brian2 changes)
2. [x] Support first brian2 version that uses `pytest` (brian2 commit brian-team/brian2@1156cfa73550bbba83a62c27a20c82b126629c3b)
    - Transition brian2cuda from `nosetest` to `pytest`
    - Compare brian2 PR for that transition (brian-team/brian2#1127)
    - Make sure #171 is solved and close it

## 2. Transition from Python 2 to Python 3 (#161)
1. [x] Support last brian2 version that supports Python 2 (release 2.3: brian-team/brian2@96210923bcb9fe953f11a)
    - Should be minor changes after above's update
2. [x] Support first brian2 version that dropped python 2 support (brian-team/brian2@ed7040834d57ebee10a9c6a4566476e48cf9cd0)
    - Transition brian2cuda to Python 3
    - Compare brian2 PR (brian-team/brian2#1147)
    - Close brian2cuda issue #161

## 3. Update to most recent brian2 release
- [x] At the time of writing, that is brian2 release 2.4.2, which should (hopefully) be minor changes after the Python 3 update
    - If it wasn't closed before, this should close #170

**Comment by denisalevi** [comment]
Done :tada:
